mywdir : "~/DIMEt/example2/"
datadi : "data/"
extrulist_fi : "mets_toexclude_ldh.csv"

names_compartments : # set abreviations (better), or rewrite the same compartment names
  cell : "cell"
  med : "med"
  
namesuffix : "metldh"
metadata_fi : "metadataLDH_endo_exo.csv"
name_abundances : "ALL_abundance_total.tsv"
name_isotopologue_contribs : "endo_isotopologues.tsv"


# global configuration for plotting
levelstime : ["T0", "T24", "T48"]
# note: this dataset does not have real timepoints, explanation:
# T0 : normoxia ; T24: hypoxia24h, T48 : hypoxia48h.
conditions : ["Cont", "A", "B", "AB"] # first must be control


# Differential Analysis configuration
dodiff_allisotopologues : False # set to true if willing to run for each isotopologue
max_m_species : 4 # ignored if dodiff_allisotopologues set to false

whichtest : "Tt"
technical_toexclude : []
# newcateg: column that is a combination of 2 or more metadata categories,
# new category thus generated, is ready for comparison to its counterpart;
# example :
#  Control (a condition) combined with T0 (a timepoint), yields Control_T0
#  L-Cyclo (another condition) combined with T0 (same timepoint) yields L-Cyclo_T0
# 	so now, we are able to compare L-Cyclo_T0 against Control_T0 .
newcateg : ["condition", "timepoint"]  # example 'Control_T0'

contrasts : [ ['AB_T0', 'Cont_T0']  ]# for each pair,last must be control
 


## Isotopologue Contribution plot configuration
#
#groups_toplot_isotopol_contribs:
#  cell :
#    0: []
#    1 : []
#  med :
#    0 : [  ]
#    1 : []


# Abundances plot configuration

#time_sel : ["T0", "T24"]
#selectedmets_forbars:
#  cell: []
#  med:  []

