# -----------------------------
# Config file for *DIMet*
# Note: for indentation use space (never tab!): 2 space indents
# coments start with #
# -----------------------------

# -----------------------------
# necesary to all steps
# -----------------------------

metadata_path : ~/toy_multiclass/data/metadata_mclass.csv

name_abundance : rawAbundances
name_meanE_or_fracContrib : FracContribution_C
name_isotopologue_prop : CorrectedIsotopologues # isotopologue proportions
name_isotopologue_abs : null  # isotopologue absolute values (for toy2 not avail)

conditions : 
 - Control # first must be control
 - Inhibitor
 - L-Cyclos
 - Therapy
 
suffix : mcla
out_path : ~/toy_multiclass/analysis001/


# -----------------------------
# Plots
# -----------------------------
# metabolites to plot:
metabolites_to_plot:
  cell: ["Fructose_1,6-bisphosphate", # in "quotes" because has a comma inside
         L-Lactic_acid, Pyruvic_acid, L-Malic_acid,
         Fumaric_acid, L-Alanine, L-Glutamic_acid,
         L-Glutamine, L-Aspartic_acid]
  med:  [L-Lactic_acid, Pyruvic_acid, 
           L-Alanine, L-Asparagine]


# Abundances bars configuration
# -----------------------------
time_sel :
  - T0
barcolor : timepoint
axisx : condition
axisx_labeltilt : 20 # 0 is no tilt
width_each_subfig : 3
wspace_subfigs : 1

# Isotopologue Contribution plot configuration
# -----------------------------
width_each_stack : !!float 3
wspace_stacks : !!float 1.1
numbers_size : 13


# Fractional Contributions lineplot configuration
# -----------------------------
# will run with defaults, see --help 


# -----------------------------
# differential analysis
# -----------------------------

     
thresholds:
  padj: 1
  absolute_log2FC: 0.3
  

multiclass_analysis : KW



# -------------------- end of config file ---------------------         
# NOTE: Metabolograms need a separated configuration file
