# -----------------------------
# Config file for *DIMet*
# Note: for indentation use space (never tab!): 2 space indents
# coments start with #
# -----------------------------

# -----------------------------
# necesary to all steps
# -----------------------------

metadata_path : ~/toy1/data/metadata_toy1.csv 

name_abundance : AbundanceCorrected
name_meanE_or_fracContrib : MeanEnrichment13C
name_isotopologue_prop : IsotopologuesProp # isotopologue proportions
name_isotopologue_abs : IsotopologuesAbs  # isotopologue absolute values

conditions : 
  - sgLDHA # first must be control, when several

suffix : l1
out_path : ~/toy1/analysis001/


# -----------------------------
# Plots
# -----------------------------
# metabolites to plot:
metabolites_to_plot:
  endo: [Cit, Fru1P]


# Abundances bars configuration
# -----------------------------
time_sel : 
  - T0
  - T24
barcolor : timepoint
axisx : condition
axisx_labeltilt : 20 # 0 is no tilt
width_each_subfig : 3
wspace_subfigs : 1


# Isotopologue Contribution plot configuration
# -----------------------------
width_each_stack : !!float 3
wspace_stacks : !!float 1.1
numbers_size : 13


# Fractional Contributions lineplot configuration
# -----------------------------
# will run with defaults, see --help 


# -----------------------------
# differential analysis
# -----------------------------
grouping : 
  - timepoint  # explanation at the end of this section

comparisons : 
  - [T24, T0]  # for each pair, last must be control
             
statistical_test:
  abundances: prm-scipy
  meanE_or_fracContrib: KW
  isotopologue_abs: ranksum 
  isotopologue_prop: null
     
thresholds:
  padj: 0.2
  absolute_log2FC: 3


# grouping:
#   * the category we pick for comparison (here timepoint)
#   * or, a combination of 2 metadata categories at choice (see toy 2)

# -------------------- end of config file ---------------------         
# NOTE: Metabolograms need a separated configuration file
